# Generated by Django 5.0.7 on 2024-07-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_booking_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_booked',
        ),
    ]
